- hosts: libvirt
  roles:
    - role: common
      common_hostname: "libvirt-0"

    - role: virt

    - role: gantsign.golang
      golang_gopath: "/home/lvandyke/go"  # Keep your local gopath
      golang_version: "1.23.1"  # Use the updated Golang version from upstream
      golang_redis_sha256sum: "49bbb517cfa9eee677e1e7897f7cf9cfdbcf49e05f61984a2789136de359f9bd"  # Keep the upstream checksum

    - role: helper
      helper_apt_packages: [
        "build-essential",
        "git",
        "libvirt-dev",
        "make",
      ]
      helper_sync_local_paths: [ "/Users/lvandyke/projects/Go/nomad-driver-virt" ]  # Keep your local path
