---
- name: Install Consul
  apt:
    name: "consul={{ consul_version }}*"
    state: present
  become: true

- name: Create Consul data directory
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: '0755'
  become: true

- name: Deploy Consul configuration
  template:
    src: "consul.hcl.j2"
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: consul
    group: consul
    mode: '0640'
  become: true
  notify: Restart Consul

- name: Enable Consul service
  systemd:
    name: consul
    enabled: yes
  become: true

- name: Start Consul service
  systemd:
    name: consul
    state: started
  become: true
