---
nomad_plugin_dir: "/opt/nomad/plugins"

nomad_driver_virt_version: "0.0.1-beta.1"
nomad_driver_virt_url: "https://releases.hashicorp.com/nomad-driver-virt/{{ nomad_driver_virt_version }}/nomad-driver-virt_{{ nomad_driver_virt_version }}_linux_amd64.zip"

nomad_driver_exec2_version: "0.1.0-beta.2"
nomad_driver_exec2_url: "https://releases.hashicorp.com/nomad-driver-exec2/{{ nomad_driver_exec2_version }}/nomad-driver-exec2_{{ nomad_driver_exec2_version }}_linux_amd64.zip"

nomad_virt_image_paths:
  - "/var/local/statics/images/"
